# <Murphy Glawe>             <9/25/2023>
# <Assignment #3/ spinnerWinner.py>
# <A one or twoplayer game that gather user inputs to wager points and to get as close as you can to a target value. First player with zero points loses>

import random


def printTitleMaterial(): #------- This function prints the 'title material' that prints out when the program starts.
    print("  _____ ____ ____  ____   ____     ___  ____       __    __  ____  ____   ____     ___  ____ ")     
    print(" / ___/|    \    ||    \ |    \   /  _]|    \     |  |__|  ||    ||    \ |    \   /  _]|    \  ")   
    print("(   \_ |  o  )  | |  _  ||  _  | /  [_ |  D  )    |  |  |  | |  | |  _  ||  _  | /  [_ |  D  )   ") 
    print(" \__  ||   _/|  | |  |  ||  |  ||    _]|    /     |  |  |  | |  | |  |  ||  |  ||    _]|    /     ")
    print(" /  \ ||  |  |  | |  |  ||  |  ||   [_ |    \     |  `  '  | |  | |  |  ||  |  ||   [_ |    \     ")
    print(" \    ||  |  |  | |  |  ||  |  ||     ||  .  \     \      /  |  | |  |  ||  |  ||     ||  .  \    ")
    print("  \___||__| |____||__|__||__|__||_____||__|\_|      \_/\_/  |____||__|__||__|__||_____||__|\_|    ")                                                                                              
    print()
    print("By: Murphy R. Glawe")
    print("[COM S 127 <J>]")
    print()

def initialChoice():
    # This function allows the player to make various choices when starting the game. This is an example of the 'do-while' pattern.
    choice = input("Choice? [p]lay, [i]nstructions, [q]uit: ")
    while choice != "p" and choice != "i" and choice != "q":
        print("ERROR: Please enter 'p', 'i', or 'q'...")
        choice = input("Choice? [p]lay, [i]nstructions, [q]uit: ")
    return choice 

def chooseNumPlayers():
    #This function allows the player to choose whether they will play against anotherhuman, or play against the computer.
    numPlayers = 0 
    numPlayers = (input("How many players? [1] or [2]: "))
    while numPlayers != '1' and numPlayers != '2':
        print("ERROR: Please enter [1] or [2]")
        numPlayers = input("How many players? [1] or [2]: ")
    return int(numPlayers)
    
    

def wait():
    # This function has the computer 'wait' until the [Enter] key is pressed. This allows for better 'readability' in the final output.
    input("Press [Enter] To Continue...")
    print()

def printBanner():
    # Prints the 'banner' between each round of the game so that the output text does not get too 'messy.'
    wait()
    print("#######################################################################")
    print()
    print("~~ Starting New Round ~~")
    print()

def printPoints(playerNum, points):
    # This function prints the number of points a certain player currently has. :param Integer playerNum: The player whose points are being displayed. :param Integer points: The number of points to be displayed
    print("* Player {0} Has {1} Points!".format(playerNum, points))
    print()

def wagerPointsHuman(playerNum, points):
    #  This function uses the 'do-while' pattern to take in input for the number of points to be wagered. It checks to
    # make sure that the player has entered a valid amount of points. Meaning, the player cannot wager more points than
    # they have, nor zero points, nor a negative number of points. The function then returns the wager.
    # As there could potentially be two human players, this function requires the playerNum to know which player to include
    # in any printouts.
    wager = 0
    wager = int(input(f"Player {playerNum}, how many points would you like to wager? Your points = {points}: "))
    while wager <= 0 or wager > points:
        print(f"ERROR: Player {playerNum} you cant wager 0 points or points you dont have. ")
        wager = int(input(f"Player {playerNum}, how many points would you like to wager?: "))
    return wager
   

def wagerPointsAI(playerNum, points):
    # This function should choose a random number between 1 and the number of points the AI has (inclusive). For example,
    # if the computer has 5 points, it can wager either 1, 2, 3, 4, or 5. This function should include a printout similar to 
    # what is printed when the human wagers points.
    wager = 0
    wager = random.randint(1, points)
    print(f"Player {playerNum} how many points would you like to wager? Your points = {points}: {wager}")


    return wager

def generateTargetValue(numSpinners, spinnerLow, spinnerHigh):
    # This function generates the 'target value' that the players try to match. This number is generated by summing together
    # 'numSpinners' number of spinners, between 'spinnerLow' and 'spinnerHigh' (inclusive). For example, of there are 3 spinners, 
    # and a spinner can have values between 1 - 3, then the target value would be the summation of 3 random values between 1 and 3
    # (inclusive).    
    target = 0
    numSpinners = random.randint(1, numSpinners)
    for i in range(numSpinners):
        sum = random.randint(spinnerLow, spinnerHigh)
        target += sum 
    return target
   
    

def getSpinnerChoiceHuman(playerNum, target, numSpinners, spinnerLow, spinnerHigh):
    #  This function gets the number of spinners that the human wants to spin. It should print out the 'target value' that the player
    # is trying to match, as well as the values that a spinner can produce (ex: 1 - 3), and the number of spinners that can be spun. The
    # player cannot pick more spinners than are in the game, nor can the pick zero spinners, nor can they pick a negative number of spinners.
    spinnerChoice = 0
    spinnerChoice = int(input(f"Player {playerNum} choose how many spinners you would like to spin between 1 and {numSpinners}. The amount of points a spin can generate is {spinnerLow} - {spinnerHigh} points. Your target value is {target} points. Choose: "))
    while spinnerChoice <= 0 or spinnerChoice > numSpinners:
        spinnerChoice = int(input(f"ERROR: Player {playerNum}, you must choose a valid amount of spinners between 1 and {numSpinners}. Choose: "))
    return spinnerChoice
    

def getSpinnerChoiceAI(playerNum, target, numSpinners, spinnerLow, spinnerHigh):
    #  This function gets the number of spinners that the computer wants to spin. This number should be a randomly generated value
    # between 1 and numSpinners (inclusive). It should print out text similar to what the 'getSpinnerChoiceHuman()' function produces.
    spinnerChoice = 0
    spinnerChoice = random.randint(1, numSpinners)
    print(f"Player {playerNum} choose how many spinners you would like to spin between 1 and {numSpinners}. The amount of points a spin can generate is {spinnerLow} - {spinnerHigh} points. Your target value is {target} points. Choose: {spinnerChoice}")
    print("-----------------------------------------------------------------------------------------------------------------------------------------")
    return spinnerChoice


def spinSpinners(playerNum, spinnerChoice, target, spinnerLow, spinnerHigh):
    #  This function can be used for either human or computer players, and it calculates the summed values of the number of
    # spinner spins. For example, if the player chooses to spin 3 spinners, and these spinners can have values between 1 and 3,
    # the player could spin values of 2, 3, and 1 for a total of 6. This is the value the function would return.
    # This function should print out the results of each spin as each spin is spun. The function should then print the sum of 
    # all the spins and the target value once all the spins are complete.
    # Please note - the winner of the round is *not* calculated here - only the spinner totals.
    spinNumber = 0
    spinTotal = 0 # Sum the spinVal values together with this variable.
    spinVal = 0 # Assign the output of a random number between spinnerLow and spinnerHigh (inclusive) to this variable.
    print(f"Player {playerNum} has chosen {spinnerChoice} spinners.")
    print("-----------------------------------------------------------------------------------------------------------------------------------------")
    wait()
    print("-----------------------------------------------------------------------------------------------------------------------------------------")
    for i in range(spinnerChoice):
        spinVal = random.randint(spinnerLow, spinnerHigh)
        spinNumber += 1

        print(f"Spin number {spinNumber}'s result is {spinVal} points.")
        
        spinTotal += spinVal
    print("-----------------------------------------------------------------------------------------------------------------------------------------")
    wait()
    print(f"Player {playerNum} total spinner results is {spinTotal} points.")
    print(f"The target value is {target} points.")
    print("-----------------------------------------------------------------------------------------------------------------------------------------")
    
    return spinTotal
   
    

def main():
    # This is the main function that executes when the game is started from the terminal. It contains all of the logic/ states
    # necessary to play the game.
    
    # main script running control variable
    running = True
    
    # gameplay variables
    SPINNER_LOW = 1
    SPINNER_HIGH = 3
    NUM_SPINNERS = 3
    INITIAL_POINTS = 10
    player1Points = INITIAL_POINTS
    player2Points = INITIAL_POINTS

    # print the title/ author information
    printTitleMaterial()

    # play the game
    while running:
        choice = initialChoice()
        if choice == "p":

            numPlayers = chooseNumPlayers()

            # main game loop
            while True:
                # round setup
                printBanner()

                

                # Find a target value.
                target = generateTargetValue(NUM_SPINNERS, SPINNER_LOW, SPINNER_HIGH)
                # Player 1 wager. (Player 1 will always be human.)
                player1wager = wagerPointsHuman(1, player1Points)
                spinner1choice = getSpinnerChoiceHuman(1, target, NUM_SPINNERS, SPINNER_LOW, SPINNER_HIGH)
                wait()
                # Player 2 wager. (Player 2 can be either human or AI - you must account for both.)
                if numPlayers == 1:
                    player2wager = wagerPointsAI(2, player2Points)
                    spinner2choice = getSpinnerChoiceAI(2, target, NUM_SPINNERS, SPINNER_LOW, SPINNER_HIGH)
                else:
                    player2wager = wagerPointsHuman(2, player2Points)
                    spinner2choice = getSpinnerChoiceHuman(2, target, NUM_SPINNERS, SPINNER_LOW, SPINNER_HIGH)
                    
                    
                

                
                
                spin1Total = spinSpinners(1, spinner1choice, target, SPINNER_LOW, SPINNER_HIGH) # Player 1 spin - get the total of all the spinners. (Player 1 will always be human.)
                spin2Total = spinSpinners(2, spinner2choice, target, SPINNER_LOW, SPINNER_HIGH) # Player 2 spin - get the total of all the spinners. (Player 2 can be either human or AI - you must account for both.)
                
                # Calculate Winner of the round. (If Player1 is closer, Player 1 wins. Else if Player 2 is closer Player 2 wins. If they are equal it is a draw.)
                differenceplayerone = abs(spin1Total - target)
                differenceplayertwo = abs(spin2Total - target)
                wait()
                if differenceplayerone > differenceplayertwo:
                    print("$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$")
                    print("      Player 2 Wins the round!!")
                    print("$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$")
                    player1Points -= player1wager  # Player 2vwins and gets points equal to their wager
                    player2Points += player2wager  # Player 1 loses points equal to their wager 
                elif differenceplayerone < differenceplayertwo: 
                    print("$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$")
                    print("      Player 1 Wins the round!!")
                    print("$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$")
                    player1Points += player1wager  # Player 1 wins and gets points equal to their wager
                    player2Points -= player2wager  # Player 2 loses points equal to their wager
                else: 
                    print("$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$")
                    print("               Draw!!")
                    print("$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$")
                # Print the points for both players
                wait()
                print("-----------------------------------------------------------------------------------------------------------------------------------------")
                printPoints(1, player1Points)
                wait()
                print("-----------------------------------------------------------------------------------------------------------------------------------------")
                printPoints(2, player2Points)
                if player1Points <= 0 or player2Points <= 0: # Check of the game is over - if it is, print a 'game over' message, reset the points to default values, and break out of the gameplay loop. Otherwise, print that it is the end of the round.
                    print("Game Over!")
                    if player1Points > player2Points:
                        print("$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$")
                        print("       Player 1 Wins the Game!!")
                        print("$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$")
                    elif player1Points < player2Points:
                        print("$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$")
                        print("       Player 2 Wins the Game!!")
                        print("$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$")
                    player1Points = INITIAL_POINTS
                    player2Points = INITIAL_POINTS
                    break 

        elif choice == "i":
            print("                     |||Instructions|||")
            print("1. The user selects a game between one or two players.")
            print("- 1 player = player agaisnt computer || 2 player = player against player")
            print()
            print("2. Each player starts with 10 points.")
            print()
            print("3.The game is divided into rounds")
            print("- At the start of the 'round,' the computer generates a 'target value.' This is the goal that players attempt to 'match' ")
            print()
            print("4. At the start of the 'round,' each player 'wagers' a certain number of 'points. ")
            print("- Players cannot wager more points than they have, nor can they wager zero or negative numbers")
            print()
            print("5. Then each player decides how many 'spinners' to spin")
            print("- Players can not spin more spinners than are available to be spun, nor zero or negative spinners ")
            print()
            print("6. After each player spins their spinners their spin value will be compared to the target value")
            print("- The player who gets their spin value closest to the target value is the winner of the round")
            print("- If both players spin values are equally distant from the target value the round is a draw")
            print()
            print("7. Once the winner is decided, points will be added and subtracted from each players score(unless a draw of course)")
            print()
            print("8. The game continues until one player is completely out of points")
             
        elif choice == "q":
            print("Goodbye!")
            running = False


        else:
            print("ERROR: Variable 'choice' should have been 'p', 'i', or 'q', but instead was:", choice)
            quit()

if __name__ == "__main__":
    main()
